version: "3"

services:
  mySQLcontained:
    image: "mysql:latest"
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
    volumes:
      - devphp-mysql-data:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - 3306:3306
  websvr:
    build: ./LAMPcontained
    volumes:
      - "./LAMPcontained/data:/var/www/html"
    ports:
      - 5000:80
    links:
      - mySQLcontained
    depends_on:
      - mySQLcontained

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PMAcontained
    environment:
      - PMA_HOST=${PMA_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - PMA_PORT=${PMA_PORT}
    ports:
      - 8080:80
volumes:
  devphp-mysql-data:      