version: "3"

services:
  mySQLcontained:
    image: "mysql:latest"
    restart: always
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - 3307:3306
  
  websvr:
    build: ./LAMPcontained
    volumes:
      - "./LAMPcontained/data:/var/www/html"
    ports:
      - 5000:80
    links:
      - mySQLcontained
    depends_on:
      - mySQLcontained

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PMAcontained
    environment:
      - PMA_HOST=${PMA_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_PORT=${PMA_PORT}
      
    ports:
      - 8080:80